
#include "../unity/unity.h"
#include "../inc/MK20DX256.h"
#include "../src/GPIO.h"

void setUp(void){
	GPIO_Init();
}

void test_SetPinAsOutput_should_ConfigurePinDirection(void)
{
	PORTC.PDDR=0;


	TEST_ASSERT_EQUAL(GPIO_OK,GPIO_SetPinAsOutput(0));
    TEST_ASSERT_EQUAL_HEX32(BIT_TO_MASK(0),PORTC.PDDR);
    TEST_ASSERT_EQUAL(GPIO_OK,GPIO_SetPinAsOutput(22));
    TEST_ASSERT_EQUAL_HEX32(BIT_TO_MASK(22)|BIT_TO_MASK(0),PORTC.PDDR);
    TEST_ASSERT_EQUAL(GPIO_OK,GPIO_SetPinAsOutput(31));
    TEST_ASSERT_EQUAL_HEX32(BIT_TO_MASK(22)|BIT_TO_MASK(0)|BIT_TO_MASK(31),PORTC.PDDR);
}

void test_SetPinAsOutput_should_NotUpdatePinDir_when_PinIsNotValid(void)
{
	PORTC.PDDR=0;


	TEST_ASSERT_NOT_EQUAL(GPIO_OK,GPIO_SetPinAsOutput(32));
    TEST_ASSERT_EQUAL_HEX32(0,PORTC.PDDR);
}

void test_SetPinAsOutput_should_NotChange_when_OtherPinsDir(void)
{
	PORTC.PDDR=0x111F1110;
	REGISTER finalRegVal=0x111F1111;

	TEST_ASSERT_EQUAL_INT(GPIO_OK,GPIO_SetPinAsOutput(0));
	TEST_ASSERT_EQUAL_HEX32(finalRegVal,PORTC.PDDR);
}



void test_SetPinAsInput_should_ConfigurePinDirection(void)
{
	PORTC.PDDR=0xFFFFFFFF;

	TEST_ASSERT_EQUAL_INT(GPIO_OK,GPIO_SetPinAsInput(0));
    TEST_ASSERT_EQUAL_HEX32(~(BIT_TO_MASK(0)),PORTC.PDDR);
    TEST_ASSERT_EQUAL(GPIO_OK,GPIO_SetPinAsInput(22));
    TEST_ASSERT_EQUAL_HEX32(~(BIT_TO_MASK(22)|BIT_TO_MASK(0)),PORTC.PDDR);
    TEST_ASSERT_EQUAL(GPIO_OK,GPIO_SetPinAsInput(31));
    TEST_ASSERT_EQUAL_HEX32(~(BIT_TO_MASK(22)|BIT_TO_MASK(0)|BIT_TO_MASK(31)),PORTC.PDDR);
}

void test_SetPinAsInput_should_NotUpdatePinDir_when_PinIsNotValid(void)
{
	PORTC.PDDR=0xFFFFFFFF;


	TEST_ASSERT_EQUAL_INT(GPIO_OUT_OF_RANGE,GPIO_SetPinAsInput(32));
    TEST_ASSERT_EQUAL_HEX32(0xFFFFFFFF,PORTC.PDDR);
}

void test_SetPinAsInput_should_NotChange_when_OtherPinsDir(void)
{
	PORTC.PDDR=0x111F1111;
	REGISTER finalRegVal=0x111F1110;

	TEST_ASSERT_EQUAL_INT(GPIO_OK,GPIO_SetPinAsInput(0));
	TEST_ASSERT_EQUAL_HEX32(finalRegVal,PORTC.PDDR);
}

void test_SetPin_should_SetOutputHigh(void){
	PORTC.PSOR=0;
	PORTC.PCOR=0;

	TEST_ASSERT_EQUAL_INT(GPIO_OK,GPIO_SetPin(0));
	TEST_ASSERT_EQUAL_HEX32(BIT_TO_MASK(0),PORTC.PSOR);
	TEST_ASSERT_EQUAL_HEX32(0,PORTC.PCOR);

	TEST_ASSERT_EQUAL_INT(GPIO_OK,GPIO_SetPin(31));
	TEST_ASSERT_EQUAL_HEX32(BIT_TO_MASK(31),PORTC.PSOR);
	TEST_ASSERT_EQUAL_HEX32(0,PORTC.PCOR);
}

void test_SetPin_should_NotSetPin_when_PinInvalid(void){
	PORTC.PSOR=0;
	PORTC.PCOR=0;
	PORTC.PDDR=0;

	TEST_ASSERT_EQUAL_INT(GPIO_OUT_OF_RANGE,GPIO_SetPinAsInput(32));
	TEST_ASSERT_EQUAL_HEX32(0,PORTC.PCOR);
	TEST_ASSERT_EQUAL_HEX32(0,PORTC.PSOR);
	TEST_ASSERT_EQUAL_HEX32(0,PORTC.PDDR);
}


void test_SetPin_should_ForceToOutput_when_ConfiguredAsInput(void){
	PORTC.PSOR=0;
	PORTC.PCOR=0;
	PORTC.PDDR=0x50000000;

	TEST_ASSERT_EQUAL_INT(GPIO_OK,GPIO_SetPin(0));
	TEST_ASSERT_EQUAL_HEX32(BIT_TO_MASK(0),PORTC.PSOR);
	TEST_ASSERT_EQUAL_HEX32(0,PORTC.PCOR);
	TEST_ASSERT_EQUAL_HEX32(0x50000001,PORTC.PDDR);

	TEST_ASSERT_EQUAL_INT(GPIO_OK,GPIO_SetPin(31));
	TEST_ASSERT_EQUAL_HEX32(BIT_TO_MASK(31),PORTC.PSOR);
	TEST_ASSERT_EQUAL_HEX32(0,PORTC.PCOR);
	TEST_ASSERT_EQUAL_HEX32(0xD0000001,PORTC.PDDR);


	TEST_ASSERT_EQUAL_INT(GPIO_OK,GPIO_SetPin(1));
	TEST_ASSERT_EQUAL_HEX32(BIT_TO_MASK(1),PORTC.PCOR);
	TEST_ASSERT_EQUAL_HEX32(BIT_TO_MASK(31),PORTC.PSOR);
	TEST_ASSERT_EQUAL_HEX32(0xD0000003,PORTC.PDDR);



}


void test_ClearPin_should_SetOutputLow(void)
{
	PORTC.PSOR=0;
	PORTC.PCOR=0;

	TEST_ASSERT_EQUAL_INT(GPIO_OK,GPIO_ClearPin(0));
	TEST_ASSERT_EQUAL_HEX32(BIT_TO_MASK(0),PORTC.PCOR);
	TEST_ASSERT_EQUAL_HEX32(0,PORTC.PSOR);

	TEST_ASSERT_EQUAL_INT(GPIO_OK,GPIO_ClearPin(31));
	TEST_ASSERT_EQUAL_HEX32(BIT_TO_MASK(31),PORTC.PCOR);
	TEST_ASSERT_EQUAL_HEX32(0,PORTC.PSOR);
}

void test_ClearPin_should_NotClearPin_when_PinInvalid(void){
	PORTC.PSOR=0;
	PORTC.PCOR=0;
	PORTC.PDDR=0;

	TEST_ASSERT_EQUAL_INT(GPIO_OUT_OF_RANGE,GPIO_SetPinAsInput(32));
	TEST_ASSERT_EQUAL_HEX32(0,PORTC.PCOR);
	TEST_ASSERT_EQUAL_HEX32(0,PORTC.PSOR);
	TEST_ASSERT_EQUAL_HEX32(0,PORTC.PDDR);
}

void test_ClearPin_should_ForceToOutput_when_ConfiguredAsInput(void){
	PORTC.PSOR=0;
	PORTC.PCOR=0;
	PORTC.PDDR=0x50000000;

	TEST_ASSERT_EQUAL_INT(GPIO_OK,GPIO_SetPin(0));
	TEST_ASSERT_EQUAL_HEX32(BIT_TO_MASK(0),PORTC.PSOR);
	TEST_ASSERT_EQUAL_HEX32(0,PORTC.PCOR);
	TEST_ASSERT_EQUAL_HEX32(0x50000001,PORTC.PDDR);

	TEST_ASSERT_EQUAL_INT(GPIO_OK,GPIO_SetPin(1));
	TEST_ASSERT_EQUAL_HEX32(BIT_TO_MASK(1),PORTC.PCOR);
	TEST_ASSERT_EQUAL_HEX32(BIT_TO_MASK(0),PORTC.PSOR);
	TEST_ASSERT_EQUAL_HEX32(0x50000003,PORTC.PDDR);


	TEST_ASSERT_EQUAL_INT(GPIO_OK,GPIO_SetPin(31));
	TEST_ASSERT_EQUAL_HEX32(BIT_TO_MASK(31),PORTC.PSOR);
	TEST_ASSERT_EQUAL_HEX32(BIT_TO_MASK(1),PORTC.PCOR);
	TEST_ASSERT_EQUAL_HEX32(0xD0000003,PORTC.PDDR);
}

void test_ReadPin_should_ReturnPinValue(void){
	PORTC.PSOR=0;
	PORTC.PCOR=0;
	PORTC.PDDR=0xFFFFFFFF;
	PORTC.PDIR=0x80000007;


	TEST_ASSERT_EQUAL_INT(1,GPIO_ReadPin(0));
	TEST_ASSERT_EQUAL_HEX32(0xFFFFFFFF,PORTC.PDDR);

	TEST_ASSERT_EQUAL_INT(1,GPIO_ReadPin(1));
	TEST_ASSERT_EQUAL_HEX32(0xFFFFFFFF,PORTC.PDDR);

	TEST_ASSERT_EQUAL_INT(1,GPIO_ReadPin(2));
	TEST_ASSERT_EQUAL_HEX32(0xFFFFFFFF,PORTC.PDDR);

	TEST_ASSERT_EQUAL_INT(0,GPIO_ReadPin(30));
	TEST_ASSERT_EQUAL_HEX32(0xFFFFFFFF,PORTC.PDDR);

	TEST_ASSERT_EQUAL_INT(1,GPIO_ReadPin(31));
	TEST_ASSERT_EQUAL_HEX32(0xFFFFFFFF,PORTC.PDDR);

}


void test_ReadPin_should_ReturnError_when_PinInvalid(void){
	PORTC.PSOR=0;
	PORTC.PCOR=0;
	PORTC.PDDR=0xFFFFFFFF;
	PORTC.PDIR=0x80000007;


	TEST_ASSERT_EQUAL_INT(GPIO_OUT_OF_RANGE,GPIO_ReadPin(32));
	TEST_ASSERT_EQUAL_HEX32(0xFFFFFFFF,PORTC.PDDR);
	TEST_ASSERT_EQUAL_HEX32(0x80000007,PORTC.PDIR);
	TEST_ASSERT_EQUAL_INT(GPIO_OUT_OF_RANGE,GPIO_ReadPin(33));
	TEST_ASSERT_EQUAL_HEX32(0xFFFFFFFF,PORTC.PDDR);
	TEST_ASSERT_EQUAL_HEX32(0x80000007,PORTC.PDIR);
	TEST_ASSERT_EQUAL_INT(GPIO_OUT_OF_RANGE,GPIO_ReadPin(UINT8_MAX));
	TEST_ASSERT_EQUAL_HEX32(0xFFFFFFFF,PORTC.PDDR);
	TEST_ASSERT_EQUAL_HEX32(0x80000007,PORTC.PDIR);
}

void test_ReadPort_should_ReturnPortValueWithRevPolarities(void){
	GPIO_Init();
	PORTC.PDIR=0;
	TEST_ASSERT_EQUAL_HEX32(0x00000022,GPIO_ReadPort());
	PORTC.PDIR=0xFFFFFFFF;
	TEST_ASSERT_EQUAL_HEX32(0xFFFFFFDD,GPIO_ReadPort());


}


void test_ReadPort_should_ReturnPortValue(void){
	PORTC.PSOR=0;
	PORTC.PCOR=0;
	PORTC.PDDR=0xFFFFFFFF;
	PORTC.PDIR=0x80000007;

	TEST_ASSERT_EQUAL_HEX32(0x80000025,GPIO_ReadPort());
}

void test_Init_should_ConfigurePinsToDefault(){
	PORTC.PDDR=0;
	PORTC.PSOR=0;
	PORTC.PCOR=0;

	GPIO_Init();
	TEST_ASSERT_EQUAL_HEX32(0x1012A000,PORTC.PDDR);
	TEST_ASSERT_EQUAL_HEX32(0x10102000,PORTC.PSOR);
	TEST_ASSERT_EQUAL_HEX32(0x00028000,PORTC.PCOR);
}

void test_SetPin_ShouldHandleReversedPolarity(void){
	GPIO_Init();
	PORTC.PSOR=0;
	PORTC.PCOR=0;

	TEST_ASSERT_EQUAL(GPIO_OK,GPIO_SetPin(1));
	TEST_ASSERT_EQUAL_HEX32(BIT_TO_MASK(1),PORTC.PCOR);
    TEST_ASSERT_EQUAL_HEX32(0,PORTC.PSOR);


    TEST_ASSERT_EQUAL(GPIO_OK,GPIO_SetPin(5));
    TEST_ASSERT_EQUAL_HEX32(BIT_TO_MASK(5),PORTC.PCOR);
    TEST_ASSERT_EQUAL_HEX32(0,PORTC.PSOR);

}

int main(void) {
    UNITY_BEGIN();
    RUN_TEST(test_Init_should_ConfigurePinsToDefault);
    RUN_TEST(test_ReadPort_should_ReturnPortValueWithRevPolarities);
    RUN_TEST(test_ReadPort_should_ReturnPortValue);
    RUN_TEST(test_SetPin_ShouldHandleReversedPolarity);

    RUN_TEST(test_SetPinAsOutput_should_ConfigurePinDirection);
    RUN_TEST(test_SetPinAsOutput_should_NotUpdatePinDir_when_PinIsNotValid);
    RUN_TEST(test_SetPinAsOutput_should_NotChange_when_OtherPinsDir);

    RUN_TEST(test_SetPinAsInput_should_ConfigurePinDirection);
    RUN_TEST(test_SetPinAsInput_should_NotUpdatePinDir_when_PinIsNotValid);
    RUN_TEST(test_SetPinAsInput_should_NotChange_when_OtherPinsDir);

    RUN_TEST(test_SetPin_should_SetOutputHigh);
    RUN_TEST(test_SetPin_should_NotSetPin_when_PinInvalid);
    RUN_TEST(test_SetPin_should_ForceToOutput_when_ConfiguredAsInput);


    RUN_TEST(test_ClearPin_should_SetOutputLow);
    RUN_TEST(test_ClearPin_should_NotClearPin_when_PinInvalid);
    RUN_TEST(test_ClearPin_should_ForceToOutput_when_ConfiguredAsInput);

    RUN_TEST(test_ReadPin_should_ReturnPinValue);
    RUN_TEST(test_ReadPin_should_ReturnError_when_PinInvalid);

    return UNITY_END();
}
